name: "build and test"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "debian:10"

    steps:
    - name: "dependancies"
      run: "apt-get update && apt-get install gcc g++ cmake ninja-build libwxgtk3.0-dev libgmp-dev -y"

    - uses: "actions/checkout@v2"

    - name: "configure cmake"
      run: "mkdir build && cd build && cmake --configure .. -GNinja -DCMAKE_BUILD_TYPE=Release"

    - name: "build project"
      run: "cmake --build . -j 2"
      working-directory: "build"

    - name: "make release directory"
      run: "mkdir release && cp build/shamirgui release"

    - uses: "actions/upload-artifact@v2"
      with:
        name: "shamirgui"
        path: "release"
